// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uggavrdyubrzlknchhft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnZ2F2cmR5dWJyemxrbmNoaGZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjE0MzQsImV4cCI6MjA2NTM5NzQzNH0.PQa2b3MvvdINNg5ok2-0Jy9GQyIa17ypJq-iE6-Thm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);